###############
## 
####

GPU: [0,1,2,3]

VERBOSE: True

MODEL:
  MODE: 'Deblurring_SR'
  SESSION: 'MPRNet_deblur'

# Optimization arguments.
OPTIM:
  BATCH_SIZE: 8
  NUM_EPOCHS: 22
  # NEPOCH_DECAY: [10]
  LR_INITIAL_DB: 5e-6
  LR_INITIAL: 30e-6 #3.5e-6
  LR_MIN: 1e-6
  # BETA1: 0.9

TRAINING:
  VAL_AFTER_EVERY: 1
  RESUME: False
  TRAIN_PS: 64
  VAL_PS: 64
#  TRAIN_DIR: 'D:\myprojs\data\GOPRO_Large\GOPRO_train256_4x_HDF5\LR-GOPRO_x4_Part1.h5' # path to training data
  TRAIN_DIR: '/home/misak/Desktop/REDS/Train_Renamed'    # path to LQ, GT train data
  VAL_DIR: '/home/misak/Desktop/REDS/Val300'    # path to LQ, GT validation data
  SAVE_DIR: './checkpoints'     # path to save models and images
  # SAVE_IMAGES: False
