###############
## 
####

GPU: [0,1,2,3]

VERBOSE: True

MODEL:
  MODE: 'Deblurring_SR'
  SESSION: 'MPRNet_deblur'

# Optimization arguments.
OPTIM:
  BATCH_SIZE: 10
  NUM_EPOCHS: 40
  LR_INITIAL_DB: 10e-6
  LR_INITIAL: 100e-6
  LR_MIN: 1e-6

TRAINING:
  VAL_AFTER_EVERY: 1
  RESUME: False
  TRAIN_DIR: '/home/misak/Desktop/REDS/Train_Renamed'    # path to LQ, GT train data
  VAL_DIR: '/home/misak/Desktop/REDS/Val300'    # path to LQ, GT validation data
  SAVE_DIR: './checkpoints'     # path to save models and images